(function () {
  const AIRTABLE = '/.netlify/functions/airtable-proxy';
  const BREVO = '/.netlify/functions/brevo-proxy';
  const PROJECT = 'The Final Hand';
  const STORE = { sheets: 'bleuskm_ad_call_sheets', email: 'bleuskm_ad_email_archive' };
  const $ = (id) => document.getElementById(id);
  const text = (v) => Array.isArray(v) ? v.map(text).filter(Boolean).join(', ') : String(v ?? '').trim();
  const esc = (v) => text(v).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const dateValue = (v) => { const raw = text(v); if (!raw) return 0; const value = new Date(`${raw}T12:00:00`).getTime(); return Number.isNaN(value) ? 0 : value; };
  const niceDate = (v) => { const raw = text(v); if (!raw) return ''; const value = new Date(`${raw}T12:00:00`); return Number.isNaN(value.getTime()) ? raw : value.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }); };
  const read = (key) => { try { return JSON.parse(localStorage.getItem(key) || '[]'); } catch { return []; } };
  const write = (key, rows) => localStorage.setItem(key, JSON.stringify(rows));
  async function table(name) { try { const res = await fetch(`${AIRTABLE}?table=${encodeURIComponent(name)}`); return res.ok ? (await res.json()).records || [] : []; } catch { return []; } }
  async function del(tableName, id) { return fetch(AIRTABLE, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ table: tableName, id }) }); }
  function role(fields) { return text(fields['Preferred role by Director']) || text(fields.Preferred_role_by_Director) || text(fields.Role) || text(fields['To Role']); }
  async function contacts() {
    const [crewRows, castRows] = await Promise.all([table('Crew applications'), table('Casting Submissions')]);
    const crew = crewRows.filter((r) => text(r.fields?.Status).toLowerCase() === 'core').map((r) => ({ type: 'Core Crew', name: text(r.fields?.Name) || 'Crew Member', email: text(r.fields?.Email), role: role(r.fields || {}) }));
    const cast = castRows.filter((r) => text(r.fields?.['Cast Status']).toLowerCase() === 'confirmed').map((r) => ({ type: 'Confirmed Cast', name: text(r.fields?.Name) || 'Cast Member', email: text(r.fields?.Email), role: text(r.fields?.['To Role']) || text(r.fields?.Role) }));
    return [...crew, ...cast].filter((c) => c.email);
  }
  function sortedTimeline(rows) { return [...rows].sort((a, b) => dateValue(a.fields?.['Start Date']) - dateValue(b.fields?.['Start Date'])); }
  async function renderSchedule() {
    const grid = $('scheduleCalendar'), list = $('scheduleList'); if (!grid || !list) return;
    const rows = sortedTimeline(await table('Production Timeline'));
    const firstDate = rows.map((r) => text(r.fields?.['Start Date'])).find(Boolean);
    const base = firstDate ? new Date(`${firstDate}T12:00:00`) : new Date();
    const monthStart = new Date(base.getFullYear(), base.getMonth(), 1);
    const cursor = new Date(monthStart); cursor.setDate(monthStart.getDate() - monthStart.getDay());
    if ($('scheduleMonth')) $('scheduleMonth').textContent = monthStart.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
    let html = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => `<div class="calendar-head">${day}</div>`).join('');
    for (let i = 0; i < 42; i += 1) { const day = new Date(cursor); day.setDate(cursor.getDate() + i); const key = day.toISOString().slice(0, 10); const events = rows.filter((r) => text(r.fields?.['Start Date']) === key); html += `<div class="calendar-day ${day.getMonth() === monthStart.getMonth() ? '' : 'muted'}" data-ad-date="${key}"><div class="calendar-date">${day.getDate()}</div>${events.map((r) => `<button class="calendar-event" data-ad-event="${esc(r.id)}">${esc(text(r.fields?.Phase) || text(r.fields?.Title) || 'Event')}<small>${esc(text(r.fields?.Status) || 'Upcoming')}</small></button>`).join('')}</div>`; }
    grid.innerHTML = html;
    list.innerHTML = rows.map((r) => { const f = r.fields || {}; return `<article class="item compact"><div class="item-head"><div><span class="date-chip">${esc(niceDate(f['Start Date']))}${text(f['End Date']) ? ' - ' + esc(niceDate(f['End Date'])) : ''}</span><h4>${esc(text(f.Phase) || text(f.Title) || 'Event')}</h4>${text(f.Description) ? `<p>${esc(text(f.Description))}</p>` : ''}</div><span class="badge">${esc(text(f.Status) || 'Upcoming')}</span></div><div class="mini-actions"><button data-ad-event="${esc(r.id)}">Edit</button><button class="danger" data-ad-delete-event="${esc(r.id)}">Delete</button></div></article>`; }).join('') || '<p class="meta">No schedule events yet.</p>';
  }
  function modal(html) { $('modalBody').innerHTML = html; $('modal').classList.remove('hidden'); }
  function closeModal() { $('modal').classList.add('hidden'); $('modalBody').innerHTML = ''; }
  async function eventModal(id, date) {
    const rows = await table('Production Timeline'); const row = rows.find((r) => r.id === id); const f = row?.fields || {};
    modal(`<h2>${id ? 'Edit Event' : 'New Event'}</h2><div class="modal-form"><input id="adEvTitle" placeholder="Event title" value="${esc(text(f.Phase) || text(f.Title))}"><input id="adEvStart" type="date" value="${esc(text(f['Start Date']) || date || '')}"><input id="adEvEnd" type="date" value="${esc(text(f['End Date']) || date || '')}"><select id="adEvStatus"><option>Upcoming</option><option>Active</option><option>Complete</option></select><textarea id="adEvDesc" rows="3" placeholder="Description">${esc(text(f.Description))}</textarea><button id="adEvSave">Save Event</button></div>`);
    $('adEvStatus').value = text(f.Status) || 'Upcoming';
    $('adEvSave').onclick = async () => { const fields = { Phase: text($('adEvTitle').value) || 'Untitled Event', 'Start Date': $('adEvStart').value || null, 'End Date': $('adEvEnd').value || null, Status: $('adEvStatus').value, Description: text($('adEvDesc').value) }; await fetch(AIRTABLE, { method: id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ table: 'Production Timeline', id, fields }) }); closeModal(); renderSchedule(); };
  }
  function callSheetHtml(sheet) { return `<div class="callsheet-preview"><h2>${esc(sheet.title)}</h2><div class="callsheet-grid"><p><strong>Date</strong><br>${esc(sheet.date)}</p><p><strong>Day</strong><br>${esc(sheet.day)}</p><p><strong>General Call</strong><br>${esc(sheet.call)}</p><p><strong>Location</strong><br>${esc(sheet.location)}</p><p><strong>Parking</strong><br>${esc(sheet.parking)}</p><p><strong>Nearest Hospital</strong><br>${esc(sheet.hospital)}</p><p><strong>Weather</strong><br>${esc(sheet.weather)}</p><p><strong>Production</strong><br>${PROJECT}</p></div><p><strong>Scenes / Set Descriptions</strong><br>${esc(sheet.scenes)}</p><p><strong>Set Notes</strong><br>${esc(sheet.notes)}</p></div>`; }
  function printSheet(sheet) { const win = window.open('', '_blank'); if (!win) return alert('Allow pop-ups to print.'); win.document.write(`<!doctype html><html><head><title>${esc(sheet.title)}</title><style>body{font-family:Arial,sans-serif;background:#fff;color:#111;padding:28px}.callsheet-preview{border:2px solid #111;padding:20px}.callsheet-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}h2{border-bottom:2px solid #111;padding-bottom:10px}</style></head><body>${callSheetHtml(sheet)}</body></html>`); win.document.close(); win.focus(); setTimeout(() => win.print(), 250); }
  function renderCallSheets() { const list = $('callSheetList'); if (!list) return; const sheets = read(STORE.sheets); list.innerHTML = sheets.map((sheet) => `<article class="item compact"><div class="item-head"><div><h4>${esc(sheet.title)}</h4><p>${esc(niceDate(sheet.date))} ${sheet.call ? '- ' + esc(sheet.call) : ''}</p><span class="meta">${sheet.recipients?.length || 0} recipients</span></div><span class="badge">${esc(sheet.status || 'Draft')}</span></div><div class="mini-actions"><button data-ad-preview-sheet="${esc(sheet.id)}">Preview</button><button data-ad-print-sheet="${esc(sheet.id)}">Print</button><button class="danger" data-ad-delete-sheet="${esc(sheet.id)}">Delete</button></div></article>`).join('') || '<p class="meta">No call sheets saved yet.</p>'; }
  async function renderEmail() { const wrap = $('emailRecipients'); if (!wrap) return; const group = $('emailGroup')?.value || 'all'; const rows = (await contacts()).filter((c) => group === 'all' || (group === 'crew' && c.type === 'Core Crew') || (group === 'cast' && c.type === 'Confirmed Cast')); wrap.innerHTML = rows.map((c) => `<label class="checkline"><input type="checkbox" value="${esc(c.email)}"><span>${esc(c.name)}<br><small>${esc(c.type)} - ${esc(c.email)}</small></span></label>`).join('') || '<p class="meta">No recipients in this group.</p>'; const sent = read(STORE.email); $('emailArchive').innerHTML = sent.slice(0, 12).map((m) => `<article class="item compact"><div class="item-head"><div><h4>${esc(m.subject)}</h4><p>${esc(m.from)} to ${m.count} recipient${m.count === 1 ? '' : 's'}</p><span class="meta">${esc(m.sentAt)}</span></div><span class="badge">Sent</span></div></article>`).join('') || '<p class="meta">No emails sent from this dashboard session yet.</p>'; }
  function selectedEmailRecipients() { const checked = [...document.querySelectorAll('#emailRecipients input:checked')].map((input) => input.value); const manual = text($('emailToManual')?.value).split(',').map((x) => x.trim()).filter(Boolean); return [...new Set([...checked, ...manual])]; }
  async function sendHubEmail() { const recipients = selectedEmailRecipients(); const from = $('emailFrom').value; const subject = text($('emailSubject').value); const body = text($('emailBody').value); if (!recipients.length) return alert('Select or enter at least one recipient.'); if (!subject || !body) return alert('Add a subject and message.'); for (const email of recipients) { const res = await fetch(BREVO, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ endpoint: 'https://api.brevo.com/v3/smtp/email', payload: { sender: { email: from, name: 'BLEUSKM Studios' }, to: [{ email }], subject, htmlContent: `<p>${esc(body).replace(/\n/g, '<br>')}</p>`, textContent: body } }) }); if (!res.ok) return alert(`Email failed for ${email}`); } const archive = read(STORE.email); archive.unshift({ id: Date.now(), from, subject, count: recipients.length, sentAt: new Date().toLocaleString() }); write(STORE.email, archive); $('emailSubject').value = ''; $('emailBody').value = ''; $('emailToManual').value = ''; renderEmail(); alert('Email sent.'); }
  function switchTab(tab) { const btn = document.querySelector(`.tabs button[data-tab="${tab}"]`); if (!btn) return; document.querySelectorAll('.tabs button').forEach((b) => b.classList.toggle('active', b === btn)); document.querySelectorAll('.panel').forEach((p) => p.classList.toggle('active', p.id === `tab-${tab}`)); if ($('pageLabel')) $('pageLabel').textContent = btn.textContent.toUpperCase(); }
  function bind() {
    $('emailGroup')?.addEventListener('change', renderEmail); $('selectEmailRecipients')?.addEventListener('click', () => document.querySelectorAll('#emailRecipients input').forEach((input) => { input.checked = true; })); $('clearEmailRecipients')?.addEventListener('click', () => document.querySelectorAll('#emailRecipients input').forEach((input) => { input.checked = false; })); $('sendHubEmail')?.addEventListener('click', sendHubEmail);
    document.addEventListener('click', async (event) => { const date = event.target.closest('[data-ad-date]'); if (date && !event.target.closest('[data-ad-event]')) { event.preventDefault(); event.stopPropagation(); eventModal('', date.dataset.adDate); return; } const emailBtn = event.target.closest('[data-email]'); if (emailBtn) { event.preventDefault(); event.stopPropagation(); switchTab('email'); $('emailToManual').value = emailBtn.dataset.email; $('emailSubject').focus(); return; } const eventBtn = event.target.closest('[data-ad-event]'); if (eventBtn) { event.preventDefault(); event.stopPropagation(); eventModal(eventBtn.dataset.adEvent); return; } const deleteEvent = event.target.closest('[data-ad-delete-event]'); if (deleteEvent && confirm('Delete this event for everyone?')) { await del('Production Timeline', deleteEvent.dataset.adDeleteEvent); renderSchedule(); return; } const sheets = read(STORE.sheets); const preview = event.target.closest('[data-ad-preview-sheet]'); if (preview) { const sheet = sheets.find((s) => s.id === preview.dataset.adPreviewSheet); if (sheet) modal(callSheetHtml(sheet)); return; } const print = event.target.closest('[data-ad-print-sheet]'); if (print) { const sheet = sheets.find((s) => s.id === print.dataset.adPrintSheet); if (sheet) printSheet(sheet); return; } const remove = event.target.closest('[data-ad-delete-sheet]'); if (remove) { write(STORE.sheets, sheets.filter((s) => s.id !== remove.dataset.adDeleteSheet)); renderCallSheets(); } }, true);
  }
  function boot() { renderSchedule(); renderCallSheets(); renderEmail(); }
  document.addEventListener('DOMContentLoaded', () => { bind(); setTimeout(boot, 400); });
  setInterval(() => { renderCallSheets(); if (document.querySelector('#tab-schedule.active')) renderSchedule(); }, 2500);
})();
